print("Nama kamu siapa?")
s1 = input()
print("Halo selamat siang "+ s1)
print("Darimana asal kamu Bintang?")
s2 = input()
print("Wah dari "+ s2)
print("Sebelumnya bersekolah dimana?")
s3 = input()
print("Pasti menyenangkan bersekolah di "+ s3)